export const SET_FRIENDLIST = 'SET_FRIENDLIST';

export const SET_CURRENT_FRIEND = 'SET_CURRENT_FRIEND';

export const GET_USERINFO = 'GET_USERINFO';

export const UPDATE_TYPE = 'UPDATE_TYPE';

export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

export const SET_GROUPLIST = 'SET_GROUPLIST';

export const SET_SESSIONS = 'SET_SESSIONS';

export const SET_GROUP_USER_LIST = 'SET_GROUP_USER_LIST';

export const SET_GROUP_APPLY_LIST = 'SET_GROUP_APPLY_LIST';

export const SET_FRIEND_APPLY_LIST = 'SET_FRIEND_APPLY_LIST';

export const SET_GROUP_SESSIONS = 'SET_GROUP_SESSIONS';

